// <auto-generated />
namespace DataAccsesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_ımageFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_ımageFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202203251741126_mig_ımageFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
